/*
* EEZ PSU Firmware
* Copyright (C) 2015-present, Envox d.o.o.
*
* This program is free software: you can redistribute it and/or modify
* it under the terms of the GNU General Public License as published by
* the Free Software Foundation, either version 3 of the License, or
* (at your option) any later version.

* This program is distributed in the hope that it will be useful,
* but WITHOUT ANY WARRANTY; without even the implied warranty of
* MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
* GNU General Public License for more details.

* You should have received a copy of the GNU General Public License
* along with this program.  If not, see http://www.gnu.org/licenses.
*/

#pragma once

namespace eez {
namespace psu {
namespace gui {

enum DataEnum {
    DATA_ID_NONE,
    DATA_ID_CHANNELS,
    DATA_ID_CHANNEL_OK,
    DATA_ID_OUTPUT_STATE,
    DATA_ID_OUTPUT_MODE,
    DATA_ID_MON_VALUE,
    DATA_ID_VOLT,
    DATA_ID_CURR,
    DATA_ID_OVP,
    DATA_ID_OCP,
    DATA_ID_OPP,
    DATA_ID_OTP,
    DATA_ID_DP,
    DATA_ID_ALERT_MESSAGE,
    DATA_ID_EDIT_VALUE,
    DATA_ID_EDIT_UNIT,
    DATA_ID_EDIT_INFO,
    DATA_ID_EDIT_MODE_INTERACTIVE_MODE_SELECTOR,
    DATA_ID_EDIT_STEPS,
    DATA_ID_MODEL_INFO,
    DATA_ID_FIRMWARE_INFO
};

enum FontsEnum {
    FONT_ID_NONE,
    FONT_ID_SMALL,
    FONT_ID_MEDIUM,
    FONT_ID_LARGE,
    FONT_ID_ICONS,
    FONT_ID_LARGE_LANDSCAPE
};

enum BitmapsEnum {
    BITMAP_ID_NONE,
    BITMAP_ID_LOGO
};

enum StylesEnum {
    STYLE_ID_DEFAULT,
    STYLE_ID_DEFAULT_EDIT,
    STYLE_ID_DEFAULT_INVERSE,
    STYLE_ID_DEFAULT_DISABLED_S_LEFT,
    STYLE_ID_DEFAULT_S,
    STYLE_ID_DEFAULT_L,
    STYLE_ID_PROT_INDICATOR_S,
    STYLE_ID_MON_VALUE_L,
    STYLE_ID_MON_VALUE_L_UR,
    STYLE_ID_MON_VALUE,
    STYLE_ID_MON_VALUE_UR,
    STYLE_ID_CHANNEL_OFF_L,
    STYLE_ID_CHANNEL_ERROR,
    STYLE_ID_CHANNEL_OFF,
    STYLE_ID_PROT_INDICATOR_SET_S,
    STYLE_ID_PROT_INDICATOR_TRIP_S,
    STYLE_ID_MENU_S,
    STYLE_ID_TAB_PAGE,
    STYLE_ID_TAB_PAGE_SELECTED,
    STYLE_ID_BOTTOM_BUTTON,
    STYLE_ID_BOTTOM_BUTTON_DISABLED,
    STYLE_ID_BOTTOM_BUTTON_BACKGROUND,
    STYLE_ID_KEY,
    STYLE_ID_KEY_ICONS,
    STYLE_ID_EDIT_INFO_S,
    STYLE_ID_EDIT_VALUE_L,
    STYLE_ID_EDIT_VALUE,
    STYLE_ID_EDIT_VALUE_UR,
    STYLE_ID_EDIT_VALUE_ACTIVE,
    STYLE_ID_EDIT_VALUE_S_RIGHT,
    STYLE_ID_EDIT_VALUE_UR_S_RIGHT,
    STYLE_ID_EDIT_VALUE_ACTIVE_S_RIGHT,
    STYLE_ID_NON_INTERACTIVE_BUTTON_S,
    STYLE_ID_EDIT_MODE_SLIDER_SCALE,
    STYLE_ID_EDIT_MODE_STEP_VERTICAL_SLIDER,
    STYLE_ID_TOP_BAR_S,
    STYLE_ID_MON_VALUE_LANDSCAPE_L_RIGHT,
    STYLE_ID_CHANNEL_OFF_LANDSCAPE,
    STYLE_ID_MON_VALUE_UR_LANDSCAPE_L_RIGHT,
    STYLE_ID_EDIT_S,
    STYLE_ID_EDIT_VALUE_ACTIVE_S_LEFT,
    STYLE_ID_EDIT_VALUE_S_LEFT,
    STYLE_ID_EDIT_VALUE_LEFT,
    STYLE_ID_EDIT_VALUE_ACTIVE_LEFT,
    STYLE_ID_BOTTOM_BUTTON_TEXTUAL,
    STYLE_ID_DEFAULT_EDIT_INVERSE,
    STYLE_ID_STYLE_TRTMRT
};

enum PagesEnum {
    PAGE_ID_WELCOME,
    PAGE_ID_ENTERING_STANDBY,
    PAGE_ID_STANDBY,
    PAGE_ID_MAIN_OLD,
    PAGE_ID_EDIT_MODE_SLIDER,
    PAGE_ID_EDIT_MODE_STEP,
    PAGE_ID_EDIT_MODE_KEYPAD,
    PAGE_ID_YES_NO,
    PAGE_ID_MAIN,
    PAGE_ID_SYS_PROFILES,
    PAGE_ID_SYS_INFO_NOT_FINISHED,
    PAGE_ID_MAIN_HELP,
    PAGE_ID_EDIT_NUMERIC,
    PAGE_ID_EDIT_ALPHA,
    PAGE_ID_CH_SETTINGS_PROT,
    PAGE_ID_CH_SETTINGS_PROT_SET_PWR,
    PAGE_ID_CH_SETTINGS_PROT_CLEAR,
    PAGE_ID_CH_SETTINGS_ADV,
    PAGE_ID_CH_SETTINGS_ADV_LRIPPLE,
    PAGE_ID_CH_SETTINGS_ADV_LIMITS,
    PAGE_ID_CH_SETTINGS_ADV_RSENSE,
    PAGE_ID_CH_SETTINGS_ADV_RPROG,
    PAGE_ID_CH_SETTINGS_DISP,
    PAGE_ID_CH_SETTINGS_INFO,
    PAGE_ID_SYS_SETTINGS,
    PAGE_ID_SYS_SETTINGS_CAL,
    PAGE_ID_SYS_SETTINGS_CAL_WIZ1,
    PAGE_ID_SYS_SETTINGS_CAL_WIZ2,
    PAGE_ID_SYS_SETTINGS_CAL_WIZ3,
    PAGE_ID_SYS_SETTINGS_CAL_WIZ,
    PAGE_ID_SYS_SETTINGS_CAL_WIZ_1
};

extern const uint8_t *fonts[];

struct Bitmap {
    uint16_t w;
    uint16_t h;
    const uint8_t *pixels PROGMEM;
};

extern Bitmap bitmaps[];

extern const uint8_t document[];

}
}
} // namespace eez::psu::gui
